version: '3.3'
services:
  dbserver:
    image: postgres:alpine
    environment:
      POSTGRES_USER: distribuida_784c_user
      POSTGRES_PASSWORD: d5Ll3FNuTH1U9xNJNR45oypG9GZwkM6I
      POSTGRES_DB: distribuida_784c
    ports:
      - "54321:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev 
      -ui 
      -bind=0.0.0.0 
      -client=0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:3.0.4
    command: |
      --api.insecure=true
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.endpoint.address=consul:8500
      --providers.consulCatalog.refreshInterval=10s
    ports:
      - "8080:8080"
      - "7070:80"
    expose:
      - 80
    depends_on:
      - consul
  clientes-service:
    image: paulmlp/app-clientes
    environment:
      QUARKUS_DATASOURCE_USERNAME: distribuida_784c_user
      QUARKUS_DATASOURCE_PASSWORD: d5Ll3FNuTH1U9xNJNR45oypG9GZwkM6I
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dpg-cqdbqh9u0jms738magng-a.oregon-postgres.render.com/distribuida_784c
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  productos-service:
    image: paulmlp/app-productos
    environment:
      QUARKUS_DATASOURCE_USERNAME: distribuida_784c_user
      QUARKUS_DATASOURCE_PASSWORD: d5Ll3FNuTH1U9xNJNR45oypG9GZwkM6I
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dpg-cqdbqh9u0jms738magng-a.oregon-postgres.render.com/distribuida_784c
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  ordenes-compras-service:
    image: paulmlp/app-ordenes-compras
    environment:
      QUARKUS_DATASOURCE_USERNAME: distribuida_784c_user
      QUARKUS_DATASOURCE_PASSWORD: d5Ll3FNuTH1U9xNJNR45oypG9GZwkM6I
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dpg-cqdbqh9u0jms738magng-a.oregon-postgres.render.com/distribuida_784c
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  vue-app:
      image: paulmlp/vue-app
      ports:
        - "8081:80"
      restart: always