api:
  insecure: true
  dashboard: true

entrypoints:
  http:
    address: ":7070"

providers:
  consulCatalog:
    refreshInterval: 10s
    exposedByDefault: false
    endpoint:
      address: 127.0.0.1:8500